planetapp/models.py
from flask_login import UserMixin

from .extensions import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), nullable=False, unique=True)
    email = db.Column(db.String(30), nullable=False, unique=True)
    password = db.Column(db.String(255), nullable=False)
    birth_date = db.Column(db.Date, nullable=False)
    bio = db.Column(db.String)
    settings = db.relationship("Settings", uselist=False, back_populates="user")


class Planet(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False, unique=True)
    title = db.Column(db.String(20), nullable=False, unique=True)
    image_url = db.Column(db.String(255), nullable=False)
    desc = db.Column(db.String, nullable=False)


class Settings(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    zoom = db.Column(db.Integer, nullable=False)
    speed = db.Column(db.Integer, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))
    user = db.relationship("User", back_populates="settings")

planetapp/forms.py
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, EmailField, TextAreaField, DateField
from wtforms.validators import InputRequired, Length, ValidationError
from .models import User


class UserForm(FlaskForm):
    username = StringField(validators=[
        InputRequired(), Length(min=4, max=20)], render_kw={"placeholder": "Username"})

    email = EmailField(validators=[
        InputRequired(), Length(min=4, max=30)], render_kw={"placeholder": "Email"})

    birth_date = DateField(validators=[
        InputRequired()], render_kw={"placeholder": "Birth date"})

    bio = TextAreaField(render_kw={"placeholder": "Bio"})


class RegisterForm(UserForm):
    password = PasswordField(validators=[
        InputRequired(), Length(min=8, max=20)], render_kw={"placeholder": "Password"})

    submit = SubmitField('Register')

    def validate_username(self, username):
        existing_user_username = User.query.filter_by(
            username=username.data).first()
        if existing_user_username:
            raise ValidationError('That username already exists. Please choose a different one.')

    def validate_email(self, email):
        existing_user_email = User.query.filter_by(
            email=email.data).first()
        if existing_user_email:
            raise ValidationError('That email already exists. Please choose a different one.')


class EditProfileForm(UserForm):
    submit = SubmitField('Submit changes')

    def validate_username(self, username):
        existing_user = User.query.filter_by(
            username=username.data).first()
        if existing_user and existing_user.username != current_user.username:
            raise ValidationError('That username already exists. Please choose a different one.')

    def validate_email(self, email):
        existing_user = User.query.filter_by(
            email=email.data).first()
        if existing_user and existing_user.email != current_user.email:
            raise ValidationError('That email already exists. Please choose a different one.')


class LoginForm(FlaskForm):
    username = StringField(validators=[
        InputRequired(), Length(min=4, max=20)], render_kw={"placeholder": "Username"})

    password = PasswordField(validators=[
        InputRequired(), Length(min=8, max=20)], render_kw={"placeholder": "Password"})

    submit = SubmitField('Login')

planetapp/__init__.py
from flask import Flask, render_template

from .api import api
from .auth import auth
from .extensions import bcrypt, db, login_manager
from .views import views
from config import Config


def page_not_found(e):
    return render_template('404.html'), 404


def internal_server_error(e):
    return render_template('500.html'), 500


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    app.register_blueprint(views)
    app.register_blueprint(auth)
    app.register_blueprint(api)

    app.register_error_handler(404, page_not_found)
    app.register_error_handler(500, internal_server_error)

    with app.app_context():
        db.create_all()

    return app

planetapp/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, logout_user, login_user, current_user
from .extensions import db, bcrypt, login_manager
from .forms import LoginForm, RegisterForm, EditProfileForm
from .models import User

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('views.index'))
            else:
                flash('Incorrect password')
        else:
            flash('User does not exist')
    return render_template('login.html', form=form)


@auth.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
            new_user = User(username=form.username.data, password=hashed_password, email=form.email.data, birth_date=form.birth_date.data, bio=form.bio.data)
            db.session.add(new_user)
            db.session.commit()
            return redirect(url_for('auth.login'))
        else:
            flash('Username or email is not available')

    return render_template('register.html', form=form)


@auth.route('/profile')
def profile():
    return render_template('profile.html')


@auth.route('/edit-profile', methods=['GET', 'POST'])
def edit_profile():
    form = EditProfileForm(obj=current_user)

    if request.method == 'POST':
        if form.validate_on_submit():
            form.populate_obj(current_user)
            db.session.commit()
            return redirect(url_for('auth.profile'))
        else:
            flash('Username or email is not available')

    return render_template('edit-profile.html', form=form)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

planetapp/views.py
from flask import Blueprint, render_template
from flask_login import current_user

from planetapp import db
from planetapp.models import Planet, Settings

views = Blueprint('views', __name__)


@views.route('/')
def index():
    return render_template('index.html')


@views.route('/wiki/', defaults={'planet_name': 'sun'})
@views.route('/wiki/<planet_name>')
def wiki(planet_name):
    planet = db.session.query(Planet).filter_by(name=planet_name).one()
    return render_template('wiki.html', planet=planet)


@views.route('/animation')
def animation():
    settings = db.session.query(Settings).filter_by(user_id=current_user.id).first() if current_user.is_authenticated else None
    return render_template('animation.html', settings=settings)

planetapp/templates/animation.html
{% extends "base.html" %}
{% set active_page = "animation" %}
{% block content %}
<br/>
    <div class="container">
        <h1>Solar System Animation</h1>
        <div class="row">
            <div class="col">
                <canvas id="canvas" width="1024px" height="600px"></canvas>
            </div>
            <div class="col">
                <h5>Zoom: <span id="zoom-value">{{ settings.zoom / 100 if settings else 1 }}</span></h5>
                <input class="form-range" id="zoom" type="range" min="50" max="200" value="{{ settings.zoom if settings else 100 }}" />
                <h5>Speed: <span id="speed-value">{{ settings.speed / 100 if settings else 1 }}</span></h5>
                <input class="form-range" id="speed" type="range" min="0" max="200" value="{{ settings.speed if settings else 100 }}" />
                {% if current_user.is_authenticated %}
                <hr>
                <div class="container">
                    <button type="button" id="save-settings" class="btn btn-primary m-2">Save your settings</button>
                    <button type="button" id="restore-settings" class="btn btn-danger m-2">Restore default settings</button>
                    <div id="info" class="m-2"></div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
<br/>
<script src="{{url_for('static', filename='js/animation.js')}}"></script>
{% endblock %}

planetapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        {%- block head %}
        <meta charset="UTF-8">
        <title>{% block title %}{{ title|default("Planets", true) }}{% endblock title %}</title>
        <link rel="icon" href="{{url_for('static', filename='assets/planet-logo.png')}}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/lux/bootstrap.min.css">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/simplePagination.js/1.6/jquery.simplePagination.min.js"></script>
        <srcript src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></srcript>
        <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
        {%- endblock head %}
    </head>

    <body>
        {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container">
              <a class="navbar-brandar" href="/"><div class="logo-image"><img src="{{url_for('static', filename='assets/planet-logo.png')}}" width="50" height="50"></div></a>
              <a class="navbar-brand" href="/" style="font-size: 25px">&nbsp;&nbsp;PLANETS</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                    aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item active">
                  <a class="nav-link {{ 'active' if active_page == 'index' else '' }}" href="/">Home</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link {{ 'active' if active_page == 'wiki' else '' }}" href="/wiki">Wiki</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link {{ 'active' if active_page == 'animation' else '' }}" href="/animation">Animation</a>
                </li>
              </ul>
              <div class="nav-item dropdown">
                <button type="button" class="btn btn-light nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><img src="https://www.ordinatrix.com/wp-content/uploads/2018/06/user.png" style="max-height: 30px; max-width: 30px;"></button>
              <div class="dropdown-menu">
              {% if current_user.is_authenticated %}
              <a class="dropdown-item" style="font-size: 17px">Logged as: <strong style="font-size: 17px">{{ current_user.username }}</strong></a>
              <a class="dropdown-item" href="/profile">View profile</a>
              <a class="dropdown-item" href="/edit-profile">Edit profile</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item text-muted"  href="/logout">Log out</a>
              {% else %}
              <a class="dropdown-item" disabled ><strong style="font-size: 17px">Not logged in</strong></a>
              <a class="dropdown-item" href="/login">Log in</a>
                  <div class="dropdown-divider"></div>
              <a class="dropdown-item text-muted" href="/register">Create account</a>
              {% endif %}
              </div>
              </div>
              </div>
          </div>
        </nav>
        {%- endblock navbar %}
        <br/>
        {% block body -%}
        {% for message in get_flashed_messages() %}
        <div class="alert alert-dismissible fade show alert-warning" style="text-align: center" >
          <button type="button" class="btn-close fade" data-bs-dismiss="alert"></button>
          {{ message }}
        </div>
        {% endfor %}
        {% block content -%}
        {%- endblock content %}
        {% block scripts %}
        {%- endblock scripts %}
        {%- endblock body %}
        <div class="container-fluid">
        <hr class="my-4">
        <footer class="footer py-3" style="background-color: white; bottom: auto; text-align: center">
            <span class="text-muted" style="text-align: center">Made by: Kacper Syrnik</span><br/>
            <small class="text-muted" style="font-size: 10px; text-align: center">2022, Planets | <a href="/terms">Terms & Conditions</a></small>
        </footer>
        </div>

    </body>
</html>

planetapp/templates/edit-profile.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h3>Edit Your Profile</h3>
        <hr class="my-4">


        <div class="container" style="max-width: 500px;">
          <form action="{{ url_for('auth.edit_profile') }}" method="post">
              {{  form.hidden_tag() }}
              {{  form.username.label(class="form-label") }}
              {{  form.username(class="form-control", placeholder="Enter username") }}
              <br/>
              {{  form.email.label(class="form-label") }}
              {{  form.email(class="form-control", placeholder="Enter email") }}
              <br/>
              {{  form.birth_date.label(class="form-label") }}
              {{  form.birth_date(class="form-control", placeholder="Birth date") }}
              <br/>
              {{  form.bio.label(class="form-label") }}
              {{  form.bio(class="form-control", placeholder="Bio", rows="4") }}
              <br/>
              {{ form.submit(class="btn btn-primary", style="width: 100%") }}
              <br/><br/><br/>
          </form>
          {% for message in get_flashed_messages() %}
            <div class="alert alert-dismissible fade show alert-warning" style="text-align: center" >
              <button type="button" class="btn-close fade" data-bs-dismiss="alert"></button>
              {{ message }}
            </div>
          {% endfor %}
        </div>

    </div>

{% endblock %}

planetapp/templates/index.html
{% extends "base.html" %}
{% set active_page = "index" %}
{% block content %}
<br/>
    <div class="container">
        <h1>Hello Houston!</h1>
        <hr>
        <p>Are you interested in astronomy?<br>If so, this is the perfect place for you. Here you can learn a lot about the planets and also see interesting animations.</p>
        <div class="row">
            <img src="{{url_for('static', filename='assets/astronaut.png')}}" alt="astronaut" width="400" height="400" class="col-md-auto">
            <h4 class="col align-self-center">Have a good time! :D</h4>
        </div>
    </div>
<br/>
<script src="{{url_for('static', filename='js/main.js')}}"></script>
{% endblock %}

planetapp/templates/login.html
<!DOCTYPE html>
<html lang="en">

    <head>
        {%- block head %}
        <meta charset="UTF-8">
        <title>{% block title %}{{ title|default("Planets", true) }}{% endblock title %}</title>
        <link rel="icon" href="{{url_for('static', filename='assets/planet-logo.png')}}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/lux/bootstrap.min.css">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/simplePagination.js/1.6/jquery.simplePagination.min.js"></script>
        <srcript src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></srcript>
        <link rel="stylesheet" href="style.css">
        {%- endblock head %}
    </head>
    <body>
        <div class="container">
            <div class="page-header py-5">
                <h1 style="text-align: center">Login</h1>
            </div>
        </div>
        <div class="container form-group has-danger" style="max-width: 500px;">
            <form action="{{ url_for('auth.login') }}" method="post">
                {{  form.hidden_tag() }}
                {{  form.username.label(class="form-label") }}
                {{  form.username(class="form-control", placeholder="Enter username") }}
                <br/>
                {{  form.password.label(class="form-label") }}
                {{  form.password(class="form-control", placeholder="Password") }}
                <br/>
                {{ form.submit(class="btn btn-primary", style="width: 100%") }}
                <br/><br/>
                <div style="text-align: center;"><a href="/register">Create account</a></div>
                <br/><br/><br/>
            </form>
            {% for message in get_flashed_messages() %}
            <div class="alert alert-dismissible fade show alert-warning" style="text-align: center" >
              <button type="button" class="btn-close fade" data-bs-dismiss="alert"></button>
              {{ message }}
            </div>
            {% endfor %}
        </div>
    </body>
</html>

planetapp/templates/profile.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h3>Your Profile</h3>
        <hr class="my-4">
        <div style="display: inline-block"><h5>Username:</h5></div><div style="display: inline-block"><a>&nbsp;&nbsp;{{ current_user.username }}</a></div>
        <br/>
        <div style="display: inline-block"><h5>Email:</h5></div><div style="display: inline-block"><a>&nbsp;&nbsp;{{ current_user.email }}</a></div>
        <br/>
        <div style="display: inline-block"><h5>Birth date:</h5></div><div style="display: inline-block"><a>&nbsp;&nbsp;{{ current_user.birth_date }}</a></div>
        <br/>
        <div style="display: inline-block"><h5>Bio:</h5></div><div style="display: inline-block"><a>&nbsp;&nbsp;{{ current_user.bio }}</a></div>
        <hr class="my-4">
    </div>

{% endblock %}

planetapp/templates/register.html
<!DOCTYPE html>
<html lang="en">

    <head>
        {%- block head %}
        <meta charset="UTF-8">
        <title>{% block title %}{{ title|default("Planets", true) }}{% endblock title %}</title>
        <link rel="icon" href="{{url_for('static', filename='assets/planet-logo.png')}}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/lux/bootstrap.min.css">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/simplePagination.js/1.6/jquery.simplePagination.min.js"></script>
        <srcript src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></srcript>
        <link rel="stylesheet" href="style.css">
        {%- endblock head %}
    </head>
    <body>
      <div class="container">
          <div class="page-header py-5">
              <h1 style="text-align: center">Registration</h1>
          </div>
      </div>

      <div class="container" style="max-width: 500px;">
          <form action="{{ url_for('auth.register') }}" method="post">
              {{  form.hidden_tag() }}
              {{  form.username.label(class="form-label") }}
              {{  form.username(class="form-control", placeholder="Enter username") }}
              <br/>
              {{  form.email.label(class="form-label") }}
              {{  form.email(class="form-control", placeholder="Enter email") }}
              <br/>
              {{  form.password.label(class="form-label") }}
              {{  form.password(class="form-control", placeholder="Password") }}
              <br/>
              {{  form.birth_date.label(class="form-label") }}
              {{  form.birth_date(class="form-control", placeholder="Birth date") }}
              <br/>
              {{  form.bio.label(class="form-label") }}
              {{  form.bio(class="form-control", placeholder="Bio", rows="4") }}
              <br/>
              {{ form.submit(class="btn btn-primary", style="width: 100%") }}
              <br/><br/><br/>
          </form>
          {% for message in get_flashed_messages() %}
            <div class="alert alert-dismissible fade show alert-warning" style="text-align: center" >
              <button type="button" class="btn-close fade" data-bs-dismiss="alert"></button>
              {{ message }}
            </div>
          {% endfor %}
      </div>
    </body>
</html>

planetapp/templates/wiki.html
{% extends "base.html" %}
{% set active_page = "wiki" %}
{% block content %}
<br/>
    <div class="row">
        <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-white col-md-auto">
          <div class="position-sticky">
            <div class="list-group list-group-flush mx-3 mt-4">
              <a href="/wiki/sun" class="list-group-item list-group-item-action py-2 ripple {{ 'active' if planet.name == 'sun' else '' }}"><span>Sun</span></a>
              <a href="/wiki/mercury" class="list-group-item list-group-item-action py-2 ripple {{ 'active' if planet.name == 'mercury' else '' }}"><span>Mercury</span></a>
              <a href="/wiki/venus" class="list-group-item list-group-item-action py-2 ripple {{ 'active' if planet.name == 'venus' else '' }}"><span>Venus</span></a>
              <a href="/wiki/earth" class="list-group-item list-group-item-action py-2 ripple {{ 'active' if planet.name == 'earth' else '' }}"><span>Earth</span></a>
              <a href="/wiki/mars" class="list-group-item list-group-item-action py-2 ripple {{ 'active' if planet.name == 'mars' else '' }}"><span>Mars</span></a>
              <a href="/wiki/jupiter" class="list-group-item list-group-item-action py-2 ripple {{ 'active' if planet.name == 'jupiter' else '' }}"><span>Jupiter</span></a>
              <a href="/wiki/saturn" class="list-group-item list-group-item-action py-2 ripple {{ 'active' if planet.name == 'saturn' else '' }}"><span>Saturn</span></a>
              <a href="/wiki/uranus" class="list-group-item list-group-item-action py-2 ripple {{ 'active' if planet.name == 'uranus' else '' }}"><span>Uranus</span></a>
              <a href="/wiki/neptune" class="list-group-item list-group-item-action py-2 ripple {{ 'active' if planet.name == 'neptune' else '' }}"><span>Neptune</span></a>
            </div>
          </div>
        </nav>
        <div class="col">
            <h1>{{ planet.title }}</h1>
            <hr>
            <div class="container">
                <img src="{{url_for('static', filename='assets/')}}{{ planet.image_url }}" alt="{{ planet.name }}" width="200" height="200" class="float-start m-3">
                <span>{{ planet.desc }}</span>
            </div>
        </div>
    </div>
<br/>
<script src="{{url_for('static', filename='js/main.js')}}"></script>
{% endblock %}